# render.yaml
services:
  - type: web
    name: listing-status-monitor
    env: node
    buildCommand: npm install
    startCommand: node monitor.js
    envVars:
      - key: SPARK_ACCESS_TOKEN
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: PUBLIC_WEBHOOK_URL
        sync: false
      - key: ENABLE_POLLING
        value: true
